package com.onlinebanking.autogen;

// Generated Oct 14, 2014 1:20:05 AM by Hibernate Tools 4.0.0

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3736319933856406336L;
	private Integer id;
	private String name;
	private String country;

	public Customer() {
	}

	public Customer(String name) {
		this.name = name;
	}

	public Customer(String name, String country) {
		this.name = name;
		this.country = country;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
