package com.onlinebanking.models;

// Generated Oct 19, 2014 4:55:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Requests generated by hbm2java
 */
@Entity
@Table(name = "requests", catalog = "pitchforkbank")
public class Requests implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5186186264356733568L;
	private RequestsId id;
	private User userByToUserId;
	private User userByFromUserId;
	private String type;

	public Requests() {
	}

	public Requests(RequestsId id, User userByToUserId, User userByFromUserId, String type) {
		this.id = id;
		this.userByToUserId = userByToUserId;
		this.userByFromUserId = userByFromUserId;
		this.type = type;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fromUserId", column = @Column(name = "fromUserId", nullable = false, length = 36)),
			@AttributeOverride(name = "toUserId", column = @Column(name = "toUserId", nullable = false, length = 36)) })
	public RequestsId getId() {
		return this.id;
	}

	public void setId(RequestsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "toUserId", nullable = false, insertable = false, updatable = false)
	public User getUserByToUserId() {
		return this.userByToUserId;
	}

	public void setUserByToUserId(User userByToUserId) {
		this.userByToUserId = userByToUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fromUserId", nullable = false, insertable = false, updatable = false)
	public User getUserByFromUserId() {
		return this.userByFromUserId;
	}

	public void setUserByFromUserId(User userByFromUserId) {
		this.userByFromUserId = userByFromUserId;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
